name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  shared_preferences: ^2.5.3
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  fl_chart: ^1.0.0
  flutter_typeahead: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

